FROM mongo:latest
 
# Copia os dataset e o script de inicialização para dentro da imagem
COPY json/comentarios.json /docker-entrypoint-initdb.d/
COPY json/users.json /docker-entrypoint-initdb.d/
COPY mongo-init/import.sh /docker-entrypoint-initdb.d/