# Dockerfile para a autenticação
# Usar a imagem oficial do Node.js como base
FROM node:22-alpine

# Definir a diretoria de trabalho dentro do contentor
WORKDIR /app

# Copiar os ficheiros de configuração e código para dentro da imagem
COPY package*.json ./

# Instalar as dependências
RUN npm install

# Copiar o resto do código para dentro da imagem
COPY . .

# Expor a porta em que o servidor corre (16001)
EXPOSE 16001

# Comando para iniciar o servidor
CMD ["node", "server_auth.js"]